package provider

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"
)

// Client is a thin REST client for the XIaC platform API. Every request
// carries the tenant API key in the X-Api-Key header. It talks to the same
// endpoints the platform's own web UI uses (/v1/platform/providers...).
type Client struct {
	Endpoint string
	APIKey   string
	HTTP     *http.Client
}

// NewClient builds a Client for the given endpoint + tenant API key. The
// endpoint has any trailing slash trimmed so path joins are unambiguous.
func NewClient(endpoint, apiKey string) *Client {
	return &Client{
		Endpoint: strings.TrimRight(endpoint, "/"),
		APIKey:   apiKey,
		HTTP:     http.DefaultClient,
	}
}

// do issues an HTTP request with the API key header and an optional JSON body,
// returning the raw response body and status code. It never treats a non-2xx
// as an error itself; callers decide which statuses are tolerated.
func (c *Client) do(ctx context.Context, method, path string, body any) ([]byte, int, error) {
	var reader io.Reader
	if body != nil {
		b, err := json.Marshal(body)
		if err != nil {
			return nil, 0, fmt.Errorf("marshal request: %w", err)
		}
		reader = bytes.NewReader(b)
	}

	req, err := http.NewRequestWithContext(ctx, method, c.Endpoint+path, reader)
	if err != nil {
		return nil, 0, fmt.Errorf("build request: %w", err)
	}
	req.Header.Set("X-Api-Key", c.APIKey)
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}

	httpc := c.HTTP
	if httpc == nil {
		httpc = http.DefaultClient
	}
	resp, err := httpc.Do(req)
	if err != nil {
		return nil, 0, fmt.Errorf("%s %s: %w", method, path, err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, resp.StatusCode, fmt.Errorf("read response: %w", err)
	}
	return respBody, resp.StatusCode, nil
}

// httpError builds an error including the status code and a snippet of the
// response body, for non-2xx responses the caller did not tolerate.
func httpError(method, path string, status int, body []byte) error {
	snippet := strings.TrimSpace(string(body))
	if len(snippet) > 512 {
		snippet = snippet[:512]
	}
	return fmt.Errorf("%s %s: unexpected status %d: %s", method, path, status, snippet)
}

func is2xx(status int) bool { return status >= 200 && status < 300 }

// CreateProvider registers a new AWS provider for the tenant and returns its
// id and external_id. clientExternalID is generated by the client and is
// always registered as-is.
func (c *Client) CreateProvider(ctx context.Context, regions []string, stsRegion, clientExternalID string) (id, externalID string, err error) {
	const path = "/v1/platform/providers"
	if clientExternalID == "" {
		return "", "", errors.New("external_id is required and must be generated by the client")
	}
	if regions == nil {
		regions = []string{}
	}
	payload := map[string]any{
		"kind":        "aws",
		"regions":     regions,
		"sts_region":  stsRegion,
		"external_id": clientExternalID,
	}
	body, status, err := c.do(ctx, http.MethodPost, path, payload)
	if err != nil {
		return "", "", err
	}
	if !is2xx(status) {
		return "", "", httpError(http.MethodPost, path, status, body)
	}
	var out struct {
		ID         string `json:"id"`
		ExternalID string `json:"external_id"`
	}
	if err := json.Unmarshal(body, &out); err != nil {
		return "", "", fmt.Errorf("decode create response: %w", err)
	}
	return out.ID, out.ExternalID, nil
}

// UpdateProvider updates mutable scan and STS-region settings for an existing
// tenant-scoped provider. It deliberately never sends external_id: that trust
// anchor is immutable after registration.
func (c *Client) UpdateProvider(ctx context.Context, id string, regions []string, stsRegion string) error {
	path := "/v1/platform/providers/" + id
	if regions == nil {
		regions = []string{}
	}
	body, status, err := c.do(ctx, http.MethodPut, path, map[string]any{
		"regions":    regions,
		"sts_region": stsRegion,
	})
	if err != nil {
		return err
	}
	if !is2xx(status) {
		return httpError(http.MethodPut, path, status, body)
	}
	return nil
}

// Connect attaches a cross-account role ARN to the provider and asks the
// platform to verify it. It reports whether the connection succeeded, the
// discovered account id, and a human-readable detail (which, on a read-only
// rejection, explains why).
func (c *Client) Connect(ctx context.Context, id, roleArn string) (connected bool, accountID, detail string, err error) {
	path := "/v1/platform/providers/" + id + "/connect"
	body, status, err := c.do(ctx, http.MethodPost, path, map[string]any{
		"role_arn": roleArn,
	})
	if err != nil {
		return false, "", "", err
	}
	if !is2xx(status) {
		return false, "", "", httpError(http.MethodPost, path, status, body)
	}
	var out struct {
		Connected bool   `json:"connected"`
		AccountID string `json:"account_id"`
		ReadOnly  bool   `json:"read_only"`
		Detail    string `json:"detail"`
	}
	if err := json.Unmarshal(body, &out); err != nil {
		return false, "", "", fmt.Errorf("decode connect response: %w", err)
	}
	return out.Connected, out.AccountID, out.Detail, nil
}

// GetProvider fetches the current status of a provider. A 404 is reported as
// found=false (not an error) so the resource can detect drift/deletion.
func (c *Client) GetProvider(ctx context.Context, id string) (status, accountID, externalID string, found bool, err error) {
	path := "/v1/platform/providers/" + id
	body, code, err := c.do(ctx, http.MethodGet, path, nil)
	if err != nil {
		return "", "", "", false, err
	}
	if code == http.StatusNotFound {
		return "", "", "", false, nil
	}
	if !is2xx(code) {
		return "", "", "", false, httpError(http.MethodGet, path, code, body)
	}
	var out struct {
		Status     string `json:"status"`
		AccountID  string `json:"account_id"`
		ExternalID string `json:"external_id"`
	}
	if err := json.Unmarshal(body, &out); err != nil {
		return "", "", "", false, fmt.Errorf("decode get response: %w", err)
	}
	return out.Status, out.AccountID, out.ExternalID, true, nil
}

// DeleteProvider removes a provider. A 404 is tolerated (the provider is
// already gone), so Delete is idempotent.
func (c *Client) DeleteProvider(ctx context.Context, id string) error {
	path := "/v1/platform/providers/" + id
	body, code, err := c.do(ctx, http.MethodDelete, path, nil)
	if err != nil {
		return err
	}
	if code == http.StatusNotFound || is2xx(code) {
		return nil
	}
	return httpError(http.MethodDelete, path, code, body)
}
