package provider

import (
	"context"
	"testing"

	"github.com/hashicorp/terraform-plugin-framework/resource"
)

// TestResourceSchema asserts the xiac_aws_account schema exposes the expected
// attributes with the right required/computed shape, without standing up a
// full Terraform acceptance harness.
func TestResourceSchema(t *testing.T) {
	r := NewAWSAccountResource()
	resp := &resource.SchemaResponse{}
	r.Schema(context.Background(), resource.SchemaRequest{}, resp)
	if resp.Diagnostics.HasError() {
		t.Fatalf("schema diagnostics: %v", resp.Diagnostics)
	}

	attrs := resp.Schema.Attributes
	for _, name := range []string{"id", "provider_id", "iam_role", "regions", "sts_region", "readonly", "external_id", "account_id", "status"} {
		if _, ok := attrs[name]; !ok {
			t.Fatalf("schema missing attribute %q", name)
		}
	}

	if !attrs["iam_role"].IsRequired() {
		t.Fatal("iam_role must be required")
	}
	if !attrs["id"].IsComputed() {
		t.Fatal("id must be computed")
	}
	if !attrs["external_id"].IsRequired() {
		t.Fatal("external_id must be required and generated by the client")
	}
	if !attrs["provider_id"].IsOptional() {
		t.Fatal("provider_id must be optional for app-driven adoption")
	}
	if !attrs["sts_region"].IsRequired() {
		t.Fatal("sts_region must be required after the module resolves its AWS-provider fallback")
	}
	if !attrs["account_id"].IsComputed() || !attrs["status"].IsComputed() {
		t.Fatal("account_id and status must be computed")
	}
	if !attrs["readonly"].IsOptional() || !attrs["readonly"].IsComputed() {
		t.Fatal("readonly must be optional+computed")
	}
}

// TestResourceMetadata asserts the resource type name is provider-prefixed.
func TestResourceMetadata(t *testing.T) {
	r := NewAWSAccountResource()
	resp := &resource.MetadataResponse{}
	r.Metadata(context.Background(), resource.MetadataRequest{ProviderTypeName: "xiac"}, resp)
	if resp.TypeName != "xiac_aws_account" {
		t.Fatalf("expected xiac_aws_account, got %q", resp.TypeName)
	}
}
